### ISSUE TITLE
Clarify license of proj4-esri.txt

### ISSUE THREAD

**Issue by nyalldawson** [Esri/projection-engine-db-doc#16]
The license header of proj4-esri.txt states that it's a unpublished trade secret. I suspect this is either outdated information, or that file should never have been included in this repository. Can you clarify the license?

**Comment by jgravois** [comment]
this work is licensed Apache 2.0, as stated in the README.

https://github.com/Esri/projection-engine-db-doc#licensing

I'm not seeing a file called 'proj4-esri.txt' in this repository. where exactly is it located?

**Comment by nyalldawson** [comment]
https://github.com/Esri/projection-engine-db-doc/blob/master/other/proj4-esri.txt

**Comment by jgravois** [comment]
given that the file is referenced in [README#contents](https://github.com/Esri/projection-engine-db-doc#contents), I am _pretty sure_ its inclusion was intentional.

that said, I've opened #17 to confirm. if its merged, you'll have your answer.

**Comment by nyalldawson** [comment]
Thanks @jgravois !
