### ISSUE TITLE
ESRI:31491 should not use BETA2007.gsb grid

### ISSUE THREAD

**Issue by don-vip** [Esri/projection-engine-db-doc#27]
10.8.0 [changed](https://github.com/Esri/projection-engine-db-doc/pull/14/files?file-filters%5B%5D=No+extension#diff-0e8e4615452f81489dd7fe120d6a3ddf103b6d9ca71cb8b2d9d61d721ab3517cR1383) the definition of ESRI:31491 to add `+nadgrids=BETA2007.gsb`:

```diff
 # Germany_Zone_1 [Germany Zone 1]
 # area: (lat: 55.24, 55.92) - (lon: 3.34, 4.5) [Germany - offshore North Sea west of 4.5~E]
-<31491> +proj=tmerc +ellps=bessel +x_0=1500000.0 +y_0=0.0 +lon_0=3dE +lat_0=0dN +k_0=1.0 +no_defs <>
+<31491> +proj=tmerc +ellps=bessel +x_0=1500000.0 +y_0=0.0 +lon_0=3dE +lat_0=0dN +k_0=1.0 +nadgrids=BETA2007.gsb +no_defs <>
```

Why? [It doesn't work](https://github.com/OSGeo/PROJ/issues/2508) as the extents of the BETA2007 grid (continental Germany) are reported by gdalinfo as
```
Upper Left  (   5.4166667,  55.3500000) (  5d25' 0.00"E, 55d21' 0.00"N)
Lower Right (  15.7500000,  46.9500000) ( 15d45' 0.00"E, 46d57' 0.00"N)
```

![image](https://user-images.githubusercontent.com/596867/105645951-4aa2ed00-5e9d-11eb-9b29-e90a4f94c7d8.png)

but the extents of ESRI:31491 are outside of grid bounds, as they cover the dogger bank in North Sea:

![image](https://user-images.githubusercontent.com/596867/105646360-da499b00-5e9f-11eb-891c-da7c06bd844b.png)

**Comment by RJuergens** [comment]
resolved by using PCS extents for PCS entries
