### ISSUE TITLE
Update to OSTN15

### ISSUE THREAD

**Issue by don-vip** [Esri/projection-engine-db-doc#3]
Hello,
From https://github.com/OSGeo/proj-datumgrid/issues/21#issuecomment-379740755 I see the OSTN02 NTv2 grid has been replaced by a new version called OSTN15:
https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/navigation-technology/os-net/formats-for-developers.html
The ESRI projection definitions should probably be updated to use the new grid.

**Comment by melitakennedy** [comment]
@don-vip 

Hello. Can you be more specific? This repo lists available Esri coordinate systems and transformations. There should be transformations that use the new OSTN15 grid file. On the coordinate reference systems, Esri is "late-binding", we don't have any default transformations for particular geographic CRS. That's why there's no transformation information in the PROJ.4 strings.

**Comment by don-vip** [comment]
@melitakennedy I don't know exactly. I read that "_OSTN15/OSGM15 replaced the previous models OSTN02/OSGM02_" so I assumed the grids could simply be replaced in the current definitions (ESRI:102799 to ESRI:102900) to gain more precision, but maybe that's more complicated?

I'm referring to `proj4/esri` file:
```
# OSGB36_Highways_England_A1H1 [OSGB 1936 Highways England A1H1]
# area: (lat: 50.1068, 50.4249) - (lon: -5.5482, -5.3991) [UK - Highways England - A1]
<102799> +proj=tmerc +datum=OSGB36 +x_0=261910.5587 +y_0=70975.76209 +lon_0=2dW +lat_0=49dN +k_0=0.99926 +nadgrids=OSTN02_NTv2.gsb +no_defs <>
```

**Comment by RJuergens** [comment]
We have two geographic transforms defined that go between WGS84 and OSGB1936:

   5339 GEOGTRAN["OSGB_1936_To_WGS_1984_7",GEOGCS["GCS_OSGB_1936",DATUM["D_OSGB_1936",SPHEROID["Airy_1830",6377563.396,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],METHOD["NTv2"],PARAMETER["Dataset_uk/OSTN02_NTv2",0.0]]

 108058 GEOGTRAN["WGS_1984_To_OSGB_1936_OSTN15",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],GEOGCS["GCS_OSGB_1936",DATUM["D_OSGB_1936",SPHEROID["Airy_1830",6377563.396,299.3249646]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],METHOD["NTv2"],PARAMETER["Dataset_uk/OSTN15_NTv2",0.0]]

Note that the first one (5339), which uses the OSTN02_NTv2 file, defines a transformation from OSGB36 to WGS84. The second one (108058), which uses the newer OSTN15_NTv2 file, defines a transformation from WGS84 to OSGB36.

Unlike ESRI, which uses late binding for its transformations, PROJ4 uses early binding, where any transformation is included in the CRS definition. But PROJ4 assumes that the named transformation goes from the defined CRS to WGS84. They have no way of specifying that the transformation should be reversed.

Thus, we cannot use 108058 (which is WGS84 to OSGB36), which is the better transformation, but we are stuck with using 5339 (which goes OSGB36 to WGS84).

If PROJ4 had a way to specify the ability to treat a transformation in reverse, then we could use the better transformation.

**Comment by RJuergens** [comment]
@don-vip @melitakennedy 
Comment added, but I forgot to add the email refs.

**Comment by SilverSloth** [comment]
OSTN15_NTV2 is definitely available as two files if required from Ordnance Survey. Initially they only released it in the ETRS89 to OSGB36 direction, then after pressure released it in the traditional OSGB36 to ETRS89 (proxy for WGS84). The one going to WGS84 is referenced in the epsg registry. Proj 5.0.0 onwards can use a range of Gridfiles using the new api.

**Comment by JSibbald** [comment]
When the "new" to "old" version came out I spoke to OS and told them to reissue which they did and still included the "wrong" one.  EPSG now has the OSGB_1936_To_ETRS_1989_2 as [EPSG::7709](http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:coordinateOperation:EPSG::7709) and OSGB_1936_To_WGS_1984_9 as [EPSG::7710](http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:coordinateOperation:EPSG::7710).  The gsb files are [here](https://www.ordnancesurvey.co.uk/docs/gps/OSTN15_NTv2.zip).  I have included the objedit files that work for me.
[gtf_aco.txt](https://github.com/Esri/projection-engine-db-doc/files/2483065/gtf_aco.txt)
[gtf_dat.txt](https://github.com/Esri/projection-engine-db-doc/files/2483066/gtf_dat.txt)
[gtf_ver.txt](https://github.com/Esri/projection-engine-db-doc/files/2483067/gtf_ver.txt)
