### ISSUE TITLE
Is there a way we can get WKID from WKText

### ISSUE THREAD

**Issue by naveennagar88** [Esri/projection-engine-db-doc#31]
Hi Team

Is there a way we can get a WKID from WKText

**Comment by rgwozdz** [comment]
If you have GDAL you can use `gdalsrsinfo`.

**Comment by naveennagar88** [comment]
Do we have any npm for the same ?

**Comment by rgwozdz** [comment]
I'm not aware of one, but there may be.  If so, it probably depends on there being a certain version of GDAL installed.
