### ISSUE TITLE
How to convert wkid to wkt by using this lib in javascript?

### ISSUE THREAD

**Issue by hoogw** [Esri/projection-engine-db-doc#37]
How to convert wkid to wkt by using this lib in javascript?

**Comment by beuan** [comment]
@rgwozdz, @ajturner, can you help with this questions? Thanks!

**Comment by RJuergens** [comment]
There is no code here to do that, but you could load the appropriate json/pe_list_<obj>.json file to do a lookup. the file contains both WKT1 and WKT2 strings.

**Comment by ajturner** [comment]
[This project](https://github.com/GeoXForm/spatialreference) from @rgwozdz might help
