### ISSUE TITLE
EPSG and ESRI are using different ellipsoid for POSGAR (2007 and 94) CRS

### ISSUE THREAD

**Issue by phaarnes** [Esri/projection-engine-db-doc#49]
Hi,

In the definition of CRS POSGAR 2007, there are discrepancies between EPSG and ESRI.

According to the EPSG database, this CRS uses WGS 84 as an ellipsoid. According to ESRI PE, GRS 80 is used.

See [POSGAR 2007 (EPSG:5340)](https://epsg.org/crs_5340/POSGAR-2007.html?sessionkey=p8mvb7melv) for instance.

In  [pe_list_geogcs.txt]( https://github.com/Esri/projection-engine-db-doc/blob/master/text/pe_list_geogcs.txt) the definition of this CRS is given as:

```diff
GEOGCS["GCS_POSGAR_2007",
    DATUM["D_POSGAR_2007",
    SPHEROID["GRS_1980", 6378137.0, 298.257222101]],
    PRIMEM["Greenwich", 0.0],
    UNIT["Degree", 0.0174532925199433]]
```

It's the same case for [POSGAR 94 (EPSG:4694)](https://epsg.org/crs_4694/POSGAR-94.html?sessionkey=3qi4olvio4)
```diff
GEOGCS["GCS_POSGAR_1994",
     DATUM["D_POSGAR_1994",
     SPHEROID["GRS_1980", 6378137.0, 298.257222101]],
     PRIMEM["Greenwich", 0.0],
     UNIT["Degree", 0.0174532925199433]]
```

**Comment by melitakennedy** [comment]
Thank you for reporting this! We have several, usually very old, discrepancies where EPSG updated the definitions with a minor update and we didn't at the time. We plan on updating these in the current release, hopefully (ArcGIS Pro 3.2).

**Comment by beuan** [comment]
Thank you, @phaarnes, for your feedback. Your issue should be resolved with our latest install (Update for ArcGIS Pro 3.2 https://github.com/Esri/projection-engine-db-doc/pull/53).
