### ISSUE TITLE
Wrong Base CRS for EPSG code 2176-2180

### ISSUE THREAD

**Issue by sissand** [Esri/projection-engine-db-doc#50]
IOGP changed base crs for 4 Polish projected CRS in 2021, please see https://epsg.org/closed-change-request/browse/id/2020.123.
The base CRS changed from ETRS89 (EPSG:4258) to ETRF2000-PL (9702)
This is not yet reflected in the projection engine. Can you please review and make the necessary changes?

 2176, PE_PCS_ETRS_1989_POLAND_CS2000_5
 2177, PE_PCS_ETRS_1989_POLAND_CS2000_6
 2178, PE_PCS_ETRS_1989_POLAND_CS2000_7
 2179, PE_PCS_ETRS_1989_POLAND_CS2000_8
 2180, PE_PCS_ETRS_1989_POLAND_CS92

**Comment by melitakennedy** [comment]
Hi Sissel, 

Thank you for pointing this out. We plan to fix it during the current release (ArcGIS Pro 3.2).

**Comment by beuan** [comment]
Thank you, @sissand, for your feedback. Your issue should be resolved with our latest install (Update for ArcGIS Pro 3.2 https://github.com/Esri/projection-engine-db-doc/pull/53).
