### ISSUE TITLE
Wrong name for transformation EPSG:5846 ?

### ISSUE THREAD

**Issue by sissand** [Esri/projection-engine-db-doc#51]
In geogtran_dat.txt there are 4 transformation between LUREF and WGS 84. The naming are consistent for 3 of them. 
Should the name for PE_GT_LUXEMBOURG_1930_TO_WGS_1984_3 be changed to ""LUREF_To_WGS_1984_3"?

**Comment by melitakennedy** [comment]
Hi Sissel, 

UPDATED: I didn't notice that the name of this object was a mix of the old and new names: LUREF_1930_To_WGS_1984_3. We plan to fix it in the next release.

We changed the transformation names (and the GCS name) but did not update the macro names as those are strictly used to create an object.

**Comment by beuan** [comment]
Thank you, @sissand, for your feedback. Your issue should be resolved with our latest install (Update for ArcGIS Pro 3.2 https://github.com/Esri/projection-engine-db-doc/pull/53).
