### ISSUE TITLE
pe_list_vertcs.json invalid JSON: "frameEpoch": ,

### ISSUE THREAD

**Issue by gpbmike** [Esri/projection-engine-db-doc#52]
The [pe_list_vertcs.json](https://github.com/Esri/projection-engine-db-doc/blob/4b7fac0ad138ae2d9eaab9d3a0666c6a89e8136a/json/pe_list_vertcs.json) file is filled with `"frameEpoch": ,` which is invalid JSON.

Example:
https://github.com/Esri/projection-engine-db-doc/blob/4b7fac0ad138ae2d9eaab9d3a0666c6a89e8136a/json/pe_list_vertcs.json#L19

Should it be `"frameEpoch": ""` or omitted?

**Comment by beuan** [comment]
Thank you, @gpbmike, for your feedback. Your issue should be resolved with our latest install (Update for ArcGIS Pro 3.2 https://github.com/Esri/projection-engine-db-doc/pull/53).
