### ISSUE TITLE
Error in transformation parameter for EPSG:8562

### ISSUE THREAD

**Issue by svasshus** [Esri/projection-engine-db-doc#7]
There is a small error in one of the transformations used in PE.
Example from "pe_list_geogtran.csv" file  (**EPSG:8562**):

PE is stating that it is **[""X_Axis_Translation"",-156.0]**  and that the transformation is deprecated

8562,108098,"PE_GT_NORD_SAHARA_1959_TO_WGS_1984_3","Nord_Sahara_1959_To_WGS_1984_3","GEOGTRAN[""Nord_Sahara_1959_To_WGS_1984_3"",GEOGCS[""GCS_Nord_Sahara_1959"",DATUM[""D_Nord_Sahara_1959"",SPHEROID[""Clarke_1880_RGS"",6378249.145,293.465]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],GEOGCS[""GCS_WGS_1984"",DATUM[""D_WGS_1984"",SPHEROID[""WGS_1984"",6378137.0,298.257223563]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],METHOD[""Position_Vector""],**PARAMETER[""X_Axis_Translation"",-156.0**],PARAMETER[""Y_Axis_Translation"",-87.2],PARAMETER[""Z_Axis_Translation"",287.8],PARAMETER[""X_Axis_Rotation"",0.0],PARAMETER[""Y_Axis_Rotation"",0.0],PARAMETER[""Z_Axis_Rotation"",0.814],PARAMETER[""Scale_Difference"",-0.38]]","Algeria - Hassi Messaoud","EPSG","7.11(8.1.2)",**"yes"**,"Algeria - Hassi Messaoud",31.48,32.09,5.59,6.5,10.0

However, EPSG defines the **[""X_Axis_Translation"",-156.5]** , **_NOT deprecated_**

8562,108098,"PE_GT_NORD_SAHARA_1959_TO_WGS_1984_3","Nord_Sahara_1959_To_WGS_1984_3","GEOGTRAN[""Nord_Sahara_1959_To_WGS_1984_3"",GEOGCS[""GCS_Nord_Sahara_1959"",DATUM[""D_Nord_Sahara_1959"",SPHEROID[""Clarke_1880_RGS"",6378249.145,293.465]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],GEOGCS[""GCS_WGS_1984"",DATUM[""D_WGS_1984"",SPHEROID[""WGS_1984"",6378137.0,298.257223563]],PRIMEM[""Greenwich"",0.0],UNIT[""Degree"",0.0174532925199433]],METHOD[""Position_Vector""],**PARAMETER[""X_Axis_Translation"",-156.5]**,PARAMETER[""Y_Axis_Translation"",-87.2],PARAMETER[""Z_Axis_Translation"",287.8],PARAMETER[""X_Axis_Rotation"",0.0],PARAMETER[""Y_Axis_Rotation"",0.0],PARAMETER[""Z_Axis_Rotation"",0.814],PARAMETER[""Scale_Difference"",-0.38]]","Algeria - Hassi Messaoud","EPSG","7.11(8.1.2)",**"no"**,"Algeria - Hassi Messaoud",31.48,32.09,5.59,6.5,10.0

**Comment by melitakennedy** [comment]
Hello, that was pointed out to us yesterday. We've entered an issue/bug for it and it will be fixed in the next release(s) later this year/early next year.

**Comment by jgravois** [comment]
this has been resolved in the ArcGIS Pro 2.3 / ArcGIS 10.7 release.

https://github.com/Esri/projection-engine-db-doc/releases/tag/v2.3.0

thanks!
